<a href="https://colab.research.google.com/github/Simeen01/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


```
Numpy
Pandas
Data Cleaning, Data processing - ETL
Regression models
Classification
Deep Learning
```



```
Machine Learning
1. Regression - continous variable (predict output with input given)
2. Classification - using output, predicting other outputs

#industry - 80% classification based
#47 algorithms

ML Algo:
1. Supervised - regression, classification
2. Unsupervised - clustering, Kmeans, KNN
3. Reinforcement - Deep learning, NLP
```



Numpy


*   Scientific computing library
*   Multidimentional array, matrix, linear
*   Converts image into array to read images
*   File formats - .csv , .tsv
*   






In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.ndim

2

In [ ]:
a.size

9

In [ ]:
a.shape
# 3D layers, rows, cols
# 2D rows, cols
# 1D cols

(3, 3)

In [ ]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
c = np.ones((3,3), dtype = int)
c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
c = np.zeros((3,3), dtype = int)
c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
d = np.empty((3,3), dtype = int)
d

array([[94861262146256,              0,              0],
       [             0,              0,              0],
       [             0,              0,              0]])

In [ ]:
LineSpace = np.linspace(1,20,10, retstep=True)
LineSpace

(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
        11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]),
 2.111111111111111)

Slicing

In [ ]:
a1 = np.arange(1,26).reshape(5,5)
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
a1[0:2,0:6]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
a1[1:2,1:4:2] #[r,c]

array([[7, 9]])

In [ ]:
a1[3:4,::2]

array([[16, 18, 20]])

In [ ]:
a2 = np.arange(49,98).reshape(7,7)
a2

array([[49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83],
       [84, 85, 86, 87, 88, 89, 90],
       [91, 92, 93, 94, 95, 96, 97]])

In [ ]:
#49 55
#91 97

a2[0::6,0::6]

array([[49, 55],
       [91, 97]])

In [ ]:
a2[3:3]

array([], shape=(0, 7), dtype=int64)

In [ ]:
#56 58 60 62
#77 79 81 83

a2[1::3,::2]

array([[56, 58, 60, 62],
       [77, 79, 81, 83]])

In [ ]:
#70 73 76
#91 94 97

a2[3:7:3,::3]

array([[70, 73, 76],
       [91, 94, 97]])

In [ ]:
#81 83
#95 97

a2[4:7:2,-3::2]

array([[81, 83],
       [95, 97]])

In [ ]:
#82 83
#89 90

a2[4:6,-2::]

array([[82, 83],
       [89, 90]])

In [ ]:
#converts any dimension to 1D
h = a2.flatten() #original array with no update
h

array([49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
       83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97])

In [ ]:
#converts any dimension to 1D
f = a2.ravel() #updated array
f

array([49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
       83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97])

In [ ]:
#Transpose
a2.T

array([[49, 56, 63, 70, 77, 84, 91],
       [50, 57, 64, 71, 78, 85, 92],
       [51, 58, 65, 72, 79, 86, 93],
       [52, 59, 66, 73, 80, 87, 94],
       [53, 60, 67, 74, 81, 88, 95],
       [54, 61, 68, 75, 82, 89, 96],
       [55, 62, 69, 76, 83, 90, 97]])

In [ ]:
a4 = np.arange(1,28).reshape(3,3,3)
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
a4.T

array([[[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]]])

In [ ]:
np.multiply(a1,a2)

ValueError: ignored

In [ ]:
a1.dot(a2)

ValueError: ignored

In [ ]:
a2.max()

97

In [ ]:
a2.argmax() #index of max

48

In [ ]:
a1.mean()

13.0

In [ ]:
np.square(a1)

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

In [ ]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ]])

In [ ]:
np.std(a1)

7.211102550927978

In [ ]:
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
        7.20048993e+10]])

In [ ]:
np.sin(0)

0.0

In [ ]:
np.cos(0)

1.0

In [ ]:
np.tan(0)

0.0

In [ ]:
np.log(a1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582]])

In [ ]:
np.log10(a1)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ],
       [1.32221929, 1.34242268, 1.36172784, 1.38021124, 1.39794001]])

In [ ]:
#values from 0 - 0.9, if 0-1
np.random.random((3,3))

array([[0.93277554, 0.31872319, 0.50897794],
       [0.7208611 , 0.31640855, 0.3449451 ],
       [0.02074957, 0.17026735, 0.30824043]])

In [ ]:
np.random.randint(1,4,20)

array([1, 3, 3, 1, 3, 3, 3, 1, 3, 3, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1])

In [ ]:
np.random.seed(10) #values wont change
np.random.randint(1,4,(5,5))

array([[2, 2, 1, 1, 2],
       [1, 2, 2, 1, 2],
       [2, 3, 1, 2, 1],
       [3, 1, 3, 1, 1],
       [1, 3, 1, 3, 3]])

Split function

In [ ]:
d = np.arange(1,17).reshape(4,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.split(d,2)  #type - list

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [ ]:
import numpy as np

In [ ]:
# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

def max_employment(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    max_ind = employment.argmax()
    max_country = countries[max_ind]
    max_value = employment[max_ind]

    return (max_country, max_value)

In [ ]:
max_employment(countries,employment)

('Angola', 75.69999695)

In [ ]:
# First 20 countries with school completion data
countries = np.array([
       'Algeria', 'Argentina', 'Armenia', 'Aruba', 'Austria','Azerbaijan',
       'Bahamas', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Bolivia',
       'Botswana', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Cape Verde'
])

# Female school completion rate in 2007 for those 20 countries
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

def overall_completion_rate(female_completion, male_completion):
    '''
    Fill in this function to return a NumPy array containing the overall
    school completion rate for each country. The arguments are NumPy
    arrays giving the female and male completion of each country in
    the same order.
    '''
    return (female_completion+male_completion)/2.0

In [ ]:
overall_completion_rate(female_completion, male_completion)

array([ 96.416025, 102.644275, 101.41129 ,  93.316285, 103.455575,
        98.148215, 102.35113 ,  91.77855 ,  92.835475,  89.655755,
        99.218715,  98.484275,  94.172835, 117.335125,  98.275645,
        33.04039 ,  41.905225,  90.962965,  57.08404 ,  93.06015 ])

In [ ]:
# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

# Change this country name to change what country will be printed when you
# click "Test Run". Your function will be called to determine the standardized
# score for this country for each of the given 5 Gapminder variables in 2007.
# The possible country names are available in the Downloadables section.

country_name = 'United States'

def standardize_data(values):
    '''
    Fill in this function to return a standardized version of the given values,
    which will be in a NumPy array. Each value should be translated into the
    number of standard deviations that value is away from the mean of the data.
    (A positive number indicates a value higher than the mean, and a negative
    number indicates a value lower than the mean.)
    '''
    return (values - values.mean())/values.std()

In [ ]:
standardize_data(employment)

array([-0.31965231, -0.780123  , -0.87650077,  1.82207181, -0.03051941,
       -1.99019768,  0.30144772, -0.16973184,  0.23719615,  0.84758731,
        0.18365304,  1.00821665,  0.87971351, -0.56595055, -1.07996476,
       -0.20185762,  1.38301845, -0.03051941,  1.2545153 , -1.87240259])

In [ ]:
import numpy as np

# Time spent in the classroom in the first week for 20 students
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])

def mean_time_for_paid_students(time_spent, days_to_cancel):
    '''
    Fill in this function to calculate the mean time spent in the classroom
    for students who stayed enrolled at least (greater than or equal to) 7 days.
    Unlike in Lesson 1, you can assume that days_to_cancel will contain only
    integers (there are no students who have not canceled yet).
    
    The arguments are NumPy arrays. time_spent contains the amount of time spent
    in the classroom for each student, and days_to_cancel contains the number
    of days until each student cancel. The data is given in the same order
    in both arrays.
    '''
    return time_spent[days_to_cancel >= 7].mean()

In [ ]:
mean_time_for_paid_students(time_spent, days_to_cancel)

41.05400348545454

Difference b/w flatten and ravel

In [ ]:
arr4 = np.arange(1,5).reshape(2,2)
arr4

array([[1, 2],
       [3, 4]])

In [ ]:
f = arr4.flatten()
f

array([1, 2, 3, 4])

In [ ]:
f[0] = 0
f

array([0, 2, 3, 4])

In [ ]:
r = arr4.ravel()
r

array([1, 2, 3, 4])

In [ ]:
r[0] =100
r

array([100,   2,   3,   4])

In [ ]:
arr4

array([[100,   2],
       [  3,   4]])